# Generated by Django 5.0.7 on 2024-09-03 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='mobile',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='name',
            new_name='sname',
        ),
    ]
