# Generated by Django 5.0.7 on 2024-09-07 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_remove_appointment_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='date1',
            new_name='date',
        ),
    ]
